### ISSUE TITLE
ng buil 

### ISSUE THREAD

**Issue by LeonRamos** [Uaybalam/msc#1]
✔ Browser application bundle generation complete.
✔ Copying assets complete.
✖ Index html generation failed.
Cannot read properties of undefined (reading 'setAttribute')

fix the problem and resolv de problem...

**Comment by Uaybalam** [comment]
✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files | Names   | Raw Size | Estimated Transfer Size
runtime.js          | runtime |  1.27 kB |               704 bytes

5 unchanged chunks

Build at: 2024-06-19T02:06:40.699Z - Hash: d7a53b2e2ef4b855 - Time: 2481ms

✔ Compiled successfully.
